/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.gui;

import javax.swing.WindowConstants;

/**
 *
 * @author rt
 */
public class MainFrame extends javax.swing.JFrame {

    ListFrame list = new ListFrame();
    QueueFrame queue = new QueueFrame();
    StackFrame stack = new StackFrame();
    SparseMatrixFrame matrix = new SparseMatrixFrame();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        list.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        queue.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        stack.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        matrix.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        simpleListButton = new javax.swing.JButton();
        queueButton = new javax.swing.JButton();
        stackButton = new javax.swing.JButton();
        sparseMatrixButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Escoja la Estructura a Modificar");

        simpleListButton.setText("Lista");
        simpleListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleListButtonActionPerformed(evt);
            }
        });

        queueButton.setText("Cola");
        queueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queueButtonActionPerformed(evt);
            }
        });

        stackButton.setText("Pila");
        stackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackButtonActionPerformed(evt);
            }
        });

        sparseMatrixButton.setText("Matriz Dispersa");
        sparseMatrixButton.setName(""); // NOI18N
        sparseMatrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparseMatrixButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(queueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpleListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sparseMatrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(titleLabel)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(simpleListButton)
                .addGap(18, 18, 18)
                .addComponent(queueButton)
                .addGap(18, 18, 18)
                .addComponent(stackButton)
                .addGap(18, 18, 18)
                .addComponent(sparseMatrixButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpleListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleListButtonActionPerformed
        list.setVisible(true);
    }//GEN-LAST:event_simpleListButtonActionPerformed

    private void queueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueButtonActionPerformed
        queue.setVisible(true);
    }//GEN-LAST:event_queueButtonActionPerformed

    private void stackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackButtonActionPerformed
        stack.setVisible(true);
    }//GEN-LAST:event_stackButtonActionPerformed

    private void sparseMatrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparseMatrixButtonActionPerformed
        matrix.setVisible(true);
    }//GEN-LAST:event_sparseMatrixButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton queueButton;
    private javax.swing.JButton simpleListButton;
    private javax.swing.JButton sparseMatrixButton;
    private javax.swing.JButton stackButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
